# Generated by Django 4.1.7 on 2023-03-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='modified_on',
            new_name='modified_at',
        ),
    ]
