# Generated by Django 4.1.7 on 2023-03-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_created_on_notes_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
