# Generated by Django 4.1.7 on 2023-03-08 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
